#ifndef _VARIETE_H
#define _VARIETE_H

typedef enum{
	PARFLOR,ISMAR,RIGOLAMOR,PROCRASTINO,COUCHTAR,NUIDEBOU,BUCHAFON,BELMENTION,PROMOMAJOR,ENSEIGNANT_DRESSEUR,NO_EVOLUTION
}variete;

char * chaineVariete(variete ele);
#endif
